//! HTTP client implementation for Elasticsearch and `OpenSearch` clusters.

use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::Duration;

use bytes::Bytes;
use reqwest::header::{CONTENT_ENCODING, CONTENT_TYPE};
use serde::{Deserialize, Serialize};

use crate::config::{ElasticsearchAuthConfig, ElasticsearchSinkConfig};
use crate::error::ElasticsearchError;

/// Individual error details for a rejected bulk item action.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct BulkItemError {
    /// Elasticsearch error type (e.g. `es_rejected_execution_exception`).
    #[serde(rename = "type", default)]
    pub error_type: String,
    /// Human-readable explanation of why the action was rejected.
    #[serde(default)]
    pub reason: String,
    /// Optional underlying cause details.
    #[serde(default)]
    pub caused_by: Option<serde_json::Value>,
}

/// Action item result details within a bulk response.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct BulkItem {
    /// Target index or data stream backing index name.
    #[serde(rename = "_index", default)]
    pub index: Option<String>,
    /// Document identifier.
    #[serde(rename = "_id", default)]
    pub id: Option<String>,
    /// HTTP status code for this specific document operation.
    pub status: u16,
    /// Error details if the document operation failed.
    #[serde(default)]
    pub error: Option<BulkItemError>,
}

/// Action wrapper wrapping action-specific result object (`create`, `index`, `update`, `delete`).
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct BulkItemWrapper {
    /// Result for a create action.
    #[serde(default)]
    pub create: Option<BulkItem>,
    /// Result for an index action.
    #[serde(default)]
    pub index: Option<BulkItem>,
    /// Result for an update action.
    #[serde(default)]
    pub update: Option<BulkItem>,
    /// Result for a delete action.
    #[serde(default)]
    pub delete: Option<BulkItem>,
}

impl BulkItemWrapper {
    /// Returns a reference to the inner `BulkItem` regardless of action type.
    #[must_use]
    pub fn item(&self) -> Option<&BulkItem> {
        self.create
            .as_ref()
            .or(self.index.as_ref())
            .or(self.update.as_ref())
            .or(self.delete.as_ref())
    }

    /// Returns the HTTP status code of the inner action item, if present.
    #[must_use]
    pub fn status(&self) -> Option<u16> {
        self.item().map(|i| i.status)
    }

    /// Returns the error details of the inner action item, if present.
    #[must_use]
    pub fn error(&self) -> Option<&BulkItemError> {
        self.item().and_then(|i| i.error.as_ref())
    }

    /// Returns whether this item encountered a recoverable failure (HTTP 429 or 503).
    #[must_use]
    pub fn is_recoverable(&self) -> bool {
        self.status().is_some_and(|s| s == 429 || s == 503)
    }

    /// Returns whether this item encountered an unrecoverable failure (HTTP >= 400 except 429 and 503).
    #[must_use]
    pub fn is_unrecoverable(&self) -> bool {
        self.status()
            .is_some_and(|s| s >= 400 && s != 429 && s != 503)
    }
}

/// Top-level response structure returned by the Elasticsearch/`OpenSearch` Bulk API.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct BulkResponse {
    /// Time in milliseconds spent by the cluster processing the bulk request.
    #[serde(default)]
    pub took: u64,
    /// Whether any document operations in the bulk request encountered an error.
    pub errors: bool,
    /// Array of action results for each document in the bulk request.
    #[serde(default)]
    pub items: Vec<BulkItemWrapper>,
}

impl BulkResponse {
    /// Returns the number of items that encountered a recoverable failure (HTTP 429 or 503).
    #[must_use]
    pub fn recoverable_count(&self) -> usize {
        self.items.iter().filter(|i| i.is_recoverable()).count()
    }

    /// Returns the number of items that encountered an unrecoverable failure (HTTP >= 400 except 429 and 503).
    #[must_use]
    pub fn unrecoverable_count(&self) -> usize {
        self.items.iter().filter(|i| i.is_unrecoverable()).count()
    }
}

/// Extracts line pairs (action line + document line) from an uncompressed NDJSON payload
/// for the specified item indices.
///
/// In NDJSON bulk format with autogenerated IDs, item index `i` maps to line `2*i` and line `2*i + 1`.
///
/// # Errors
///
/// Returns [`ElasticsearchError::Serialization`] if:
/// - The payload has an odd number of lines (incomplete action/document pair)
/// - Any requested item index is out of bounds
pub fn extract_sub_payload(
    payload: &[u8],
    item_indices: &[usize],
) -> Result<Bytes, ElasticsearchError> {
    if item_indices.is_empty() {
        return Ok(Bytes::new());
    }

    let mut line_ranges: Vec<(usize, usize)> = Vec::new();
    let mut line_start = 0;
    for (idx, &b) in payload.iter().enumerate() {
        if b == b'\n' {
            let line = &payload[line_start..=idx];
            if !line
                .iter()
                .all(|&c| c == b'\r' || c == b'\n' || c == b' ' || c == b'\t')
            {
                line_ranges.push((line_start, idx + 1));
            }
            line_start = idx + 1;
        }
    }
    if line_start < payload.len() {
        let line = &payload[line_start..];
        if !line
            .iter()
            .all(|&c| c == b'\r' || c == b'\n' || c == b' ' || c == b'\t')
        {
            line_ranges.push((line_start, payload.len()));
        }
    }

    if !line_ranges.len().is_multiple_of(2) {
        return Err(ElasticsearchError::Serialization(format!(
            "payload has an odd number of lines ({}), expected pairs of action and document lines",
            line_ranges.len()
        )));
    }

    let total_items = line_ranges.len() / 2;

    let mut total_bytes: usize = 0;
    for &idx in item_indices {
        if idx >= total_items {
            return Err(ElasticsearchError::Serialization(format!(
                "item index {idx} out of bounds for payload containing {total_items} items"
            )));
        }
        let action_start = line_ranges
            .get(2 * idx)
            .ok_or_else(|| {
                ElasticsearchError::Serialization(format!(
                    "missing action line range for item index {idx}"
                ))
            })?
            .0;
        let doc_end = line_ranges
            .get(2 * idx + 1)
            .ok_or_else(|| {
                ElasticsearchError::Serialization(format!(
                    "missing document line range for item index {idx}"
                ))
            })?
            .1;
        let item_len = doc_end.saturating_sub(action_start);
        total_bytes = total_bytes.saturating_add(item_len).saturating_add(1);
    }

    let mut buf = Vec::with_capacity(total_bytes);
    for &idx in item_indices {
        let action_start = line_ranges
            .get(2 * idx)
            .ok_or_else(|| {
                ElasticsearchError::Serialization(format!(
                    "missing action line range for item index {idx}"
                ))
            })?
            .0;
        let doc_end = line_ranges
            .get(2 * idx + 1)
            .ok_or_else(|| {
                ElasticsearchError::Serialization(format!(
                    "missing document line range for item index {idx}"
                ))
            })?
            .1;
        let slice = &payload[action_start..doc_end];
        buf.extend_from_slice(slice);
        if !slice.ends_with(b"\n") {
            buf.push(b'\n');
        }
    }

    Ok(Bytes::from(buf))
}

/// Internal cluster information returned by `GET /`.
#[derive(Debug, Deserialize)]
struct ClusterInfo {
    #[serde(default)]
    version: Option<ClusterVersionInfo>,
}

/// Cluster version details returned within `GET /`.
#[derive(Debug, Deserialize)]
struct ClusterVersionInfo {
    #[serde(default)]
    number: String,
}

/// Composable index template query response returned by `GET /_index_template/<pattern>`.
#[derive(Debug, Deserialize)]
struct IndexTemplatesResponse {
    #[serde(default)]
    index_templates: Vec<serde_json::Value>,
}

/// High-performance HTTP client for Elasticsearch and `OpenSearch` clusters.
///
/// Manages connection pooling, client-side round-robin endpoint selection,
/// TLS configuration, authentication header injection, and retry loops.
#[derive(Debug, Clone)]
pub struct HttpClient {
    /// Underlying reqwest HTTP client with persistent connection pool.
    client: reqwest::Client,
    /// List of normalized cluster endpoint base URLs (without trailing slashes).
    endpoints: Vec<String>,
    /// Shared atomic counter for round-robin endpoint distribution.
    current_endpoint: Arc<AtomicUsize>,
    /// Configured authentication credentials.
    auth: ElasticsearchAuthConfig,
    /// Whether gzip compression is enabled for bulk request payloads.
    gzip_compression: bool,
    /// Maximum number of retry attempts for transient failures (429/503/network).
    max_retries: usize,
    /// Delay between retries in seconds.
    retry_interval_secs: u64,
}

impl HttpClient {
    /// Constructs a new `HttpClient` from the given sink configuration.
    ///
    /// Validates endpoint list, configures TLS root CA and verification options,
    /// sets connection and request timeouts, and initializes TCP keepalive.
    pub fn try_new(config: &ElasticsearchSinkConfig) -> Result<Self, ElasticsearchError> {
        if config.endpoints.is_empty() {
            return Err(ElasticsearchError::StartupValidation(
                "at least one endpoint must be configured".to_string(),
            ));
        }

        let endpoints: Vec<String> = config
            .endpoints
            .iter()
            .map(|ep| ep.trim().trim_end_matches('/').to_string())
            .collect();

        if endpoints.iter().any(String::is_empty) {
            return Err(ElasticsearchError::StartupValidation(
                "endpoint URL cannot be empty".to_string(),
            ));
        }

        let mut builder = reqwest::Client::builder()
            .connect_timeout(Duration::from_secs(config.connect_timeout_secs))
            .timeout(Duration::from_secs(config.request_timeout_secs))
            .tcp_keepalive(Duration::from_secs(60))
            .tcp_nodelay(true)
            .gzip(true);

        if config.tls.insecure_skip_verify {
            builder = builder.danger_accept_invalid_certs(true);
        }

        if let Some(ca_path) = &config.tls.ca_cert_path {
            let pem_bytes = std::fs::read(ca_path).map_err(|e| {
                ElasticsearchError::StartupValidation(format!(
                    "failed to read CA certificate from '{ca_path}': {e}"
                ))
            })?;
            let cert = reqwest::Certificate::from_pem(&pem_bytes)?;
            builder = builder.add_root_certificate(cert);
        }

        let client = builder.build()?;

        Ok(Self {
            client,
            endpoints,
            current_endpoint: Arc::new(AtomicUsize::new(0)),
            auth: config.auth.clone(),
            gzip_compression: config.gzip_compression,
            max_retries: config.max_retries,
            retry_interval_secs: config.retry_interval_secs,
        })
    }

    /// Returns the next cluster endpoint base URL in round-robin sequence.
    #[must_use]
    pub fn next_endpoint(&self) -> &str {
        let idx = self.current_endpoint.fetch_add(1, Ordering::Relaxed);
        &self.endpoints[idx % self.endpoints.len()]
    }

    /// Returns the slice of configured cluster endpoint base URLs.
    #[must_use]
    pub fn endpoints(&self) -> &[String] {
        &self.endpoints
    }

    /// Returns a reference to the active authentication configuration.
    #[must_use]
    pub fn auth(&self) -> &ElasticsearchAuthConfig {
        &self.auth
    }

    /// Returns whether gzip compression is enabled for bulk requests.
    #[must_use]
    pub const fn gzip_compression(&self) -> bool {
        self.gzip_compression
    }

    /// Injects authentication credentials into an outgoing HTTP request builder.
    pub fn apply_auth(&self, req: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        let default_url = self
            .endpoints
            .first()
            .map_or("http://localhost:9200", |s| s.as_str());
        self.apply_auth_request(req, "GET", default_url, &[])
    }

    /// Injects authentication credentials into an outgoing HTTP request builder with explicit
    /// HTTP method, target URL, and body content for signature calculation.
    #[cfg_attr(not(feature = "aws"), allow(unused_variables))]
    pub fn apply_auth_request(
        &self,
        req: reqwest::RequestBuilder,
        method: &str,
        url: &str,
        body: &[u8],
    ) -> reqwest::RequestBuilder {
        match &self.auth {
            ElasticsearchAuthConfig::None => req,
            ElasticsearchAuthConfig::Basic { username, password } => {
                req.basic_auth(username, password.as_deref())
            }
            ElasticsearchAuthConfig::ApiKey { api_key } => {
                req.header(reqwest::header::AUTHORIZATION, format!("ApiKey {api_key}"))
            }
            ElasticsearchAuthConfig::Bearer { token } => req.bearer_auth(token),
            #[cfg(feature = "aws")]
            ElasticsearchAuthConfig::AwsSigv4 { region, service } => {
                if let (Ok(key), Ok(secret)) = (
                    std::env::var("AWS_ACCESS_KEY_ID"),
                    std::env::var("AWS_SECRET_ACCESS_KEY"),
                ) {
                    let session_token = std::env::var("AWS_SESSION_TOKEN").ok();
                    self.apply_aws_sigv4(
                        req,
                        method,
                        url,
                        body,
                        region,
                        service,
                        &key,
                        &secret,
                        session_token.as_deref(),
                    )
                } else {
                    req
                }
            }
        }
    }

    /// Signs an outgoing request with AWS `SigV4` using explicit credentials and adds signature headers.
    #[cfg(feature = "aws")]
    #[allow(clippy::too_many_arguments)]
    pub fn apply_aws_sigv4(
        &self,
        mut req: reqwest::RequestBuilder,
        method: &str,
        url: &str,
        body: &[u8],
        region: &str,
        service: &str,
        access_key: &str,
        secret_key: &str,
        session_token: Option<&str>,
    ) -> reqwest::RequestBuilder {
        let creds = aws_credential_types::Credentials::new(
            access_key,
            secret_key,
            session_token.map(ToString::to_string),
            None,
            "elasticsearch-sink",
        );
        let identity = creds.into();
        let signing_settings = aws_sigv4::http_request::SigningSettings::default();
        let Ok(signing_params) = aws_sigv4::sign::v4::SigningParams::builder()
            .identity(&identity)
            .region(region)
            .name(service)
            .time(std::time::SystemTime::now())
            .settings(signing_settings)
            .build()
        else {
            return req;
        };

        let signing_params = signing_params.into();
        let signable_body = if body.is_empty() {
            aws_sigv4::http_request::SignableBody::Bytes(&[])
        } else {
            aws_sigv4::http_request::SignableBody::Bytes(body)
        };

        let Ok(signable_request) = aws_sigv4::http_request::SignableRequest::new(
            method,
            url,
            std::iter::empty(),
            signable_body,
        ) else {
            return req;
        };

        if let Ok(output) = aws_sigv4::http_request::sign(signable_request, &signing_params) {
            let (instructions, _sig) = output.into_parts();
            for (name, val) in instructions.headers() {
                req = req.header(name, val);
            }
        }
        req
    }

    /// Returns true if an HTTP status code indicates a transient error that should be retried.
    const fn is_transient_http_status(status: reqwest::StatusCode) -> bool {
        matches!(
            status,
            reqwest::StatusCode::TOO_MANY_REQUESTS
                | reqwest::StatusCode::SERVICE_UNAVAILABLE
                | reqwest::StatusCode::BAD_GATEWAY
                | reqwest::StatusCode::GATEWAY_TIMEOUT
        )
    }

    /// Merges items from a retry response into the aggregated `final_items` vector.
    fn merge_retry_items(
        final_items: &mut [BulkItemWrapper],
        active_indices: &[usize],
        retry_items: Vec<BulkItemWrapper>,
    ) {
        for (sub_idx, item_wrapper) in retry_items.into_iter().enumerate() {
            if let Some(&orig_idx) = active_indices
                .get(sub_idx)
                .filter(|&&idx| idx < final_items.len())
            {
                final_items[orig_idx] = item_wrapper;
            }
        }
    }

    /// Dispatches a single HTTP bulk request with round-robin endpoint selection, gzip compression, and authentication.
    async fn post_bulk_request(
        &self,
        data_stream: &str,
        payload: &Bytes,
    ) -> Result<reqwest::Response, ElasticsearchError> {
        let endpoint = self.next_endpoint();
        let url = format!("{endpoint}/{data_stream}/_bulk");

        let (body, is_gzipped) = if self.gzip_compression && !payload.is_empty() {
            let mut encoder =
                flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
            std::io::Write::write_all(&mut encoder, payload).map_err(|e| {
                ElasticsearchError::Serialization(format!("gzip compression failed: {e}"))
            })?;
            let compressed = encoder.finish().map_err(|e| {
                ElasticsearchError::Serialization(format!("gzip compression finalize failed: {e}"))
            })?;
            (Bytes::from(compressed), true)
        } else {
            (payload.clone(), false)
        };

        let mut req = self
            .client
            .post(&url)
            .header(CONTENT_TYPE, "application/x-ndjson")
            .body(body.clone());

        if is_gzipped {
            req = req.header(CONTENT_ENCODING, "gzip");
        }

        req = self.apply_auth_request(req, "POST", &url, &body);
        req.send().await.map_err(ElasticsearchError::Http)
    }

    /// Inspects items in the active sub-batch to identify recoverable failures and log unrecoverable failures.
    fn inspect_active_items(
        final_items: &[BulkItemWrapper],
        active_indices: &[usize],
    ) -> Vec<usize> {
        let mut recoverable_sub_indices = Vec::new();
        let mut unrecoverable_count: usize = 0;

        for (sub_idx, &orig_idx) in active_indices.iter().enumerate() {
            if let Some(item_wrapper) = final_items.get(orig_idx) {
                if item_wrapper.is_recoverable() {
                    recoverable_sub_indices.push(sub_idx);
                } else if item_wrapper.is_unrecoverable() {
                    unrecoverable_count = unrecoverable_count.saturating_add(1);
                    let err_type = item_wrapper
                        .error()
                        .map_or("unknown", |e| e.error_type.as_str());
                    let reason = item_wrapper.error().map_or("none", |e| e.reason.as_str());
                    let doc_id = item_wrapper
                        .item()
                        .and_then(|i| i.id.as_deref())
                        .unwrap_or("none");
                    let index_name = item_wrapper
                        .item()
                        .and_then(|i| i.index.as_deref())
                        .unwrap_or("none");
                    tracing::warn!(
                        orig_index = orig_idx,
                        status = item_wrapper.status().unwrap_or(0),
                        index = %index_name,
                        doc_id = %doc_id,
                        error_type = %err_type,
                        reason = %reason,
                        "Elasticsearch bulk item rejected with unrecoverable error"
                    );
                }
            }
        }

        if unrecoverable_count > 0 {
            tracing::warn!(
                unrecoverable_count = unrecoverable_count,
                "Bulk request contained unrecoverable item errors; dropped non-retryable documents"
            );
        }

        recoverable_sub_indices
    }

    /// Sends a serialized NDJSON bulk payload targeting `POST /<data_stream>/_bulk`.
    ///
    /// Applies round-robin node selection, gzip compression (if enabled), authentication,
    /// and a jittered exponential backoff retry loop on transient failures (429/503/network).
    ///
    /// When the bulk response indicates errors (`errors: true`):
    /// - Unrecoverable item failures (HTTP 400, etc.) are logged at WARN level and dropped.
    /// - Recoverable item failures (HTTP 429, 503) are extracted by index and re-submitted
    ///   as a retry sub-payload with jittered exponential backoff and node failover.
    /// - Retries continue up to `max_retries`. If retries are exhausted and recoverable
    ///   failures remain, returns [`ElasticsearchError::BulkFailed`].
    pub async fn send_bulk(
        &self,
        data_stream: &str,
        payload: Bytes,
    ) -> Result<BulkResponse, ElasticsearchError> {
        let data_stream = data_stream.trim_matches('/');
        let max_attempts = self.max_retries.saturating_add(1);
        let mut attempt: usize = 0;

        let mut current_payload = payload;
        let mut active_indices: Vec<usize> = Vec::new();
        let mut final_items: Vec<BulkItemWrapper> = Vec::new();
        let mut total_took: u64 = 0;

        loop {
            match self.post_bulk_request(data_stream, &current_payload).await {
                Ok(response) => {
                    let status = response.status();

                    if Self::is_transient_http_status(status) {
                        attempt = attempt.saturating_add(1);
                        if attempt >= max_attempts {
                            return Err(ElasticsearchError::BulkFailed {
                                retries: self.max_retries,
                                message: format!("HTTP {status} after {attempt} attempts"),
                            });
                        }
                        self.sleep_backoff(attempt).await;
                        continue;
                    }

                    if status == reqwest::StatusCode::UNAUTHORIZED
                        || status == reqwest::StatusCode::FORBIDDEN
                    {
                        let err_text = response.text().await.unwrap_or_default();
                        return Err(ElasticsearchError::AuthenticationFailed(format!(
                            "HTTP {status}: {err_text}"
                        )));
                    }

                    if !status.is_success() {
                        let err_text = response.text().await.unwrap_or_default();
                        return Err(ElasticsearchError::BulkFailed {
                            retries: attempt,
                            message: format!("HTTP {status}: {err_text}"),
                        });
                    }

                    let bulk_resp: BulkResponse =
                        response.json().await.map_err(ElasticsearchError::Http)?;

                    total_took = total_took.saturating_add(bulk_resp.took);

                    if final_items.is_empty() {
                        if !bulk_resp.errors {
                            return Ok(bulk_resp);
                        }
                        final_items = bulk_resp.items;
                        active_indices = (0..final_items.len()).collect();
                    } else {
                        Self::merge_retry_items(&mut final_items, &active_indices, bulk_resp.items);
                    }

                    let recoverable_sub_indices =
                        Self::inspect_active_items(&final_items, &active_indices);

                    if recoverable_sub_indices.is_empty() {
                        let has_errors = final_items.iter().any(BulkItemWrapper::is_unrecoverable);
                        return Ok(BulkResponse {
                            took: total_took,
                            errors: has_errors,
                            items: final_items,
                        });
                    }

                    attempt = attempt.saturating_add(1);
                    if attempt >= max_attempts {
                        return Err(ElasticsearchError::BulkFailed {
                            retries: self.max_retries,
                            message: format!(
                                "{} items failed with recoverable status (429/503) after {} retries",
                                recoverable_sub_indices.len(),
                                self.max_retries
                            ),
                        });
                    }

                    current_payload =
                        extract_sub_payload(&current_payload, &recoverable_sub_indices)?;
                    active_indices = recoverable_sub_indices
                        .into_iter()
                        .filter_map(|sub_idx| active_indices.get(sub_idx).copied())
                        .collect();

                    self.sleep_backoff(attempt).await;
                }
                Err(err) => {
                    attempt = attempt.saturating_add(1);
                    if attempt >= max_attempts {
                        return Err(ElasticsearchError::BulkFailed {
                            retries: self.max_retries,
                            message: format!("network error after {attempt} attempts: {err}"),
                        });
                    }
                    self.sleep_backoff(attempt).await;
                }
            }
        }
    }

    /// Performs a startup cluster health check by sending `GET /`.
    ///
    /// Validates that the cluster is reachable, authenticated, and returns a valid version number.
    pub async fn health_check(&self) -> Result<(), ElasticsearchError> {
        let endpoint = self.next_endpoint();
        let url = format!("{endpoint}/");

        let req = self.client.get(&url);
        let req = self.apply_auth_request(req, "GET", &url, &[]);

        let response = req.send().await.map_err(|e| {
            ElasticsearchError::StartupValidation(format!(
                "failed to connect to cluster endpoint '{endpoint}': {e}"
            ))
        })?;

        let status = response.status();
        if status == reqwest::StatusCode::UNAUTHORIZED || status == reqwest::StatusCode::FORBIDDEN {
            return Err(ElasticsearchError::AuthenticationFailed(format!(
                "health check authentication failed with HTTP {status}"
            )));
        }

        if !status.is_success() {
            return Err(ElasticsearchError::StartupValidation(format!(
                "health check against '{endpoint}' returned HTTP {status}"
            )));
        }

        let info: ClusterInfo = response.json().await.map_err(|e| {
            ElasticsearchError::StartupValidation(format!(
                "failed to parse cluster info JSON from '{endpoint}': {e}"
            ))
        })?;

        let version_number = info
            .version
            .map(|v| v.number)
            .filter(|n| !n.trim().is_empty())
            .ok_or_else(|| {
                ElasticsearchError::StartupValidation(format!(
                    "cluster info from '{endpoint}' did not contain a valid version number"
                ))
            })?;

        tracing::info!(
            endpoint = %endpoint,
            version = %version_number,
            "Elasticsearch/OpenSearch cluster health check succeeded"
        );

        Ok(())
    }

    /// Validates that a composable index template exists for the given data stream.
    ///
    /// Queries `GET /_index_template/<data_stream>` and returns an error if not found.
    pub async fn validate_index_template(
        &self,
        data_stream: &str,
    ) -> Result<(), ElasticsearchError> {
        let data_stream = data_stream.trim_matches('/');
        let endpoint = self.next_endpoint();
        let url = format!("{endpoint}/_index_template/{data_stream}");

        let req = self.client.get(&url);
        let req = self.apply_auth_request(req, "GET", &url, &[]);

        let response = req.send().await.map_err(|e| {
            ElasticsearchError::StartupValidation(format!(
                "failed to query index template for '{data_stream}' on '{endpoint}': {e}"
            ))
        })?;

        let status = response.status();
        if status == reqwest::StatusCode::NOT_FOUND {
            return Err(ElasticsearchError::StartupValidation(format!(
                "index template for data stream '{data_stream}' not found (HTTP 404)"
            )));
        }

        if status == reqwest::StatusCode::UNAUTHORIZED || status == reqwest::StatusCode::FORBIDDEN {
            return Err(ElasticsearchError::AuthenticationFailed(format!(
                "unauthorized to validate index template for '{data_stream}': HTTP {status}"
            )));
        }

        if !status.is_success() {
            let body = response.text().await.unwrap_or_default();
            return Err(ElasticsearchError::StartupValidation(format!(
                "index template check for '{data_stream}' returned HTTP {status}: {body}"
            )));
        }

        let parsed: IndexTemplatesResponse = response.json().await.map_err(|e| {
            ElasticsearchError::StartupValidation(format!(
                "failed to parse index templates response for '{data_stream}': {e}"
            ))
        })?;

        if parsed.index_templates.is_empty() {
            return Err(ElasticsearchError::StartupValidation(format!(
                "index template for data stream '{data_stream}' returned empty template list"
            )));
        }

        tracing::info!(
            endpoint = %endpoint,
            data_stream = %data_stream,
            "Index template validation succeeded"
        );

        Ok(())
    }

    /// Executes a jittered exponential backoff sleep.
    async fn sleep_backoff(&self, attempt: usize) {
        if self.retry_interval_secs == 0 {
            tokio::task::yield_now().await;
            return;
        }

        let base_ms = self.retry_interval_secs.saturating_mul(1000).max(100);
        let shift = attempt.saturating_sub(1).min(6);
        let multiplier = 1u64 << shift;
        let base_backoff = base_ms.saturating_mul(multiplier);

        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.subsec_nanos());
        let jitter_ms = u64::from(nanos % 500);

        let total_backoff_ms = base_backoff.saturating_add(jitter_ms);
        tokio::time::sleep(Duration::from_millis(total_backoff_ms)).await;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DataStreamMapping;
    use crate::tls::TlsConfig;
    use flate2::read::GzDecoder;
    use std::io::Read;
    use wiremock::matchers::{header, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn make_test_config(endpoints: Vec<String>) -> ElasticsearchSinkConfig {
        ElasticsearchSinkConfig {
            endpoints,
            auth: ElasticsearchAuthConfig::None,
            data_streams: DataStreamMapping {
                logs: "logs-otel-default".to_string(),
                metrics: "metrics-otel-default".to_string(),
                traces: "traces-otel-default".to_string(),
            },
            tls: TlsConfig::default(),
            unpack_attributes: true,
            gzip_compression: true,
            max_concurrent_requests: 8,
            max_payload_bytes: 20_971_520,
            connect_timeout_secs: 5,
            request_timeout_secs: 10,
            max_retries: 3,
            retry_interval_secs: 0, // 0 for instantaneous tests
            validate_on_startup: true,
            batching: None,
            order_by: None,
        }
    }

    #[test]
    fn test_round_robin_endpoint_cycling() {
        let endpoints = vec![
            "http://node1:9200".to_string(),
            "http://node2:9200".to_string(),
            "http://node3:9200/".to_string(),
        ];
        let config = make_test_config(endpoints);
        let client = HttpClient::try_new(&config).unwrap();

        // Check normalization: trailing slash removed
        assert_eq!(
            client.endpoints(),
            &[
                "http://node1:9200",
                "http://node2:9200",
                "http://node3:9200"
            ]
        );

        // Verify round-robin sequence cycles evenly
        assert_eq!(client.next_endpoint(), "http://node1:9200");
        assert_eq!(client.next_endpoint(), "http://node2:9200");
        assert_eq!(client.next_endpoint(), "http://node3:9200");
        assert_eq!(client.next_endpoint(), "http://node1:9200");
        assert_eq!(client.next_endpoint(), "http://node2:9200");
        assert_eq!(client.next_endpoint(), "http://node3:9200");
    }

    #[test]
    fn test_single_endpoint_selection() {
        let endpoints = vec!["http://localhost:9200/".to_string()];
        let config = make_test_config(endpoints);
        let client = HttpClient::try_new(&config).unwrap();

        assert_eq!(client.next_endpoint(), "http://localhost:9200");
        assert_eq!(client.next_endpoint(), "http://localhost:9200");
    }

    #[test]
    fn test_empty_endpoints_rejected() {
        let config = make_test_config(vec![]);
        let err = HttpClient::try_new(&config).unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(
            err.to_string()
                .contains("at least one endpoint must be configured")
        );
    }

    #[test]
    fn test_blank_endpoint_rejected() {
        let config = make_test_config(vec!["   ".to_string()]);
        let err = HttpClient::try_new(&config).unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(err.to_string().contains("endpoint URL cannot be empty"));
    }

    #[test]
    fn test_auth_headers_none() {
        let config = make_test_config(vec!["http://localhost:9200".to_string()]);
        let client = HttpClient::try_new(&config).unwrap();

        let req = client.client.get("http://localhost:9200");
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        assert!(request.headers().get("authorization").is_none());
    }

    #[test]
    fn test_auth_headers_basic() {
        let mut config = make_test_config(vec!["http://localhost:9200".to_string()]);
        config.auth = ElasticsearchAuthConfig::Basic {
            username: "admin".to_string(),
            password: Some("secret123".to_string()),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client.client.get("http://localhost:9200");
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        let auth_hdr = request.headers().get("authorization").unwrap();
        // admin:secret123 base64 is YWRtaW46c2VjcmV0MTIz
        assert_eq!(auth_hdr.to_str().unwrap(), "Basic YWRtaW46c2VjcmV0MTIz");
    }

    #[test]
    fn test_auth_headers_basic_without_password() {
        let mut config = make_test_config(vec!["http://localhost:9200".to_string()]);
        config.auth = ElasticsearchAuthConfig::Basic {
            username: "readonly".to_string(),
            password: None,
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client.client.get("http://localhost:9200");
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        let auth_hdr = request.headers().get("authorization").unwrap();
        // readonly: base64 is cmVhZG9ubHk6
        assert_eq!(auth_hdr.to_str().unwrap(), "Basic cmVhZG9ubHk6");
    }

    #[test]
    fn test_auth_headers_api_key() {
        let mut config = make_test_config(vec!["http://localhost:9200".to_string()]);
        config.auth = ElasticsearchAuthConfig::ApiKey {
            api_key: "VnVhQ2ZHY0JDZGJrUW0tZTVhT3k6dWkybHAyYXhUTm1xWUY1QXdqd1JRdw==".to_string(),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client.client.get("http://localhost:9200");
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        let auth_hdr = request.headers().get("authorization").unwrap();
        assert_eq!(
            auth_hdr.to_str().unwrap(),
            "ApiKey VnVhQ2ZHY0JDZGJrUW0tZTVhT3k6dWkybHAyYXhUTm1xWUY1QXdqd1JRdw=="
        );
    }

    #[test]
    fn test_auth_headers_bearer() {
        let mut config = make_test_config(vec!["http://localhost:9200".to_string()]);
        config.auth = ElasticsearchAuthConfig::Bearer {
            token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9".to_string(),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client.client.get("http://localhost:9200");
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        let auth_hdr = request.headers().get("authorization").unwrap();
        assert_eq!(
            auth_hdr.to_str().unwrap(),
            "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        );
    }

    #[test]
    fn test_bulk_response_parse_success() {
        let json_str = r#"{
            "took": 42,
            "errors": false,
            "items": [
                {
                    "create": {
                        "_index": "logs-otel-default-2026.09.16-000001",
                        "_id": "doc1",
                        "status": 201
                    }
                },
                {
                    "create": {
                        "_index": "logs-otel-default-2026.09.16-000001",
                        "_id": "doc2",
                        "status": 201
                    }
                }
            ]
        }"#;

        let resp: BulkResponse = serde_json::from_str(json_str).unwrap();
        assert_eq!(resp.took, 42);
        assert!(!resp.errors);
        assert_eq!(resp.items.len(), 2);

        let item0 = resp.items[0].item().unwrap();
        assert_eq!(
            item0.index.as_deref(),
            Some("logs-otel-default-2026.09.16-000001")
        );
        assert_eq!(item0.id.as_deref(), Some("doc1"));
        assert_eq!(item0.status, 201);
        assert!(item0.error.is_none());
        assert_eq!(resp.items[0].status(), Some(201));
        assert!(resp.items[0].error().is_none());
    }

    #[test]
    fn test_bulk_response_parse_with_errors() {
        let json_str = r#"{
            "took": 88,
            "errors": true,
            "items": [
                {
                    "create": {
                        "_index": "logs-otel-default",
                        "_id": "doc1",
                        "status": 201
                    }
                },
                {
                    "create": {
                        "_index": "logs-otel-default",
                        "_id": "doc2",
                        "status": 429,
                        "error": {
                            "type": "es_rejected_execution_exception",
                            "reason": "rejected execution of queue capacity = 200"
                        }
                    }
                },
                {
                    "create": {
                        "_index": "logs-otel-default",
                        "_id": "doc3",
                        "status": 400,
                        "error": {
                            "type": "mapper_parsing_exception",
                            "reason": "failed to parse field [host.ip] of type [ip]"
                        }
                    }
                }
            ]
        }"#;

        let resp: BulkResponse = serde_json::from_str(json_str).unwrap();
        assert_eq!(resp.took, 88);
        assert!(resp.errors);
        assert_eq!(resp.items.len(), 3);

        // First item: success
        assert_eq!(resp.items[0].status(), Some(201));
        assert!(resp.items[0].error().is_none());

        // Second item: 429 rejected
        assert_eq!(resp.items[1].status(), Some(429));
        let err1 = resp.items[1].error().unwrap();
        assert_eq!(err1.error_type, "es_rejected_execution_exception");
        assert_eq!(err1.reason, "rejected execution of queue capacity = 200");

        // Third item: 400 mapping error
        assert_eq!(resp.items[2].status(), Some(400));
        let err2 = resp.items[2].error().unwrap();
        assert_eq!(err2.error_type, "mapper_parsing_exception");
        assert_eq!(err2.reason, "failed to parse field [host.ip] of type [ip]");
    }

    #[test]
    fn test_tls_config_insecure_skip_verify() {
        let mut config = make_test_config(vec!["https://localhost:9200".to_string()]);
        config.tls.insecure_skip_verify = true;
        let client = HttpClient::try_new(&config);
        assert!(client.is_ok());
    }

    #[test]
    fn test_tls_config_missing_ca_file() {
        let mut config = make_test_config(vec!["https://localhost:9200".to_string()]);
        config.tls.ca_cert_path = Some("/nonexistent/ca.pem".to_string());
        let err = HttpClient::try_new(&config).unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(
            err.to_string()
                .contains("failed to read CA certificate from '/nonexistent/ca.pem'")
        );
    }

    #[tokio::test]
    async fn test_send_bulk_success_with_gzip() {
        let server = MockServer::start().await;

        let bulk_response = r#"{
            "took": 15,
            "errors": false,
            "items": [
                {"create": {"_index": "logs-otel-default", "_id": "1", "status": 201}}
            ]
        }"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(header("content-type", "application/x-ndjson"))
            .and(header("content-encoding", "gzip"))
            .respond_with(ResponseTemplate::new(200).set_body_string(bulk_response))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();
        assert!(client.gzip_compression());

        let payload = Bytes::from("{\"create\":{}}\n{\"body\":\"test message\"}\n");
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert!(!resp.errors);
        assert_eq!(resp.took, 15);
        assert_eq!(resp.items.len(), 1);
        assert_eq!(resp.items[0].status(), Some(201));
    }

    #[tokio::test]
    async fn test_send_bulk_without_gzip() {
        let server = MockServer::start().await;

        let bulk_response = r#"{"took": 5, "errors": false, "items": []}"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(header("content-type", "application/x-ndjson"))
            .respond_with(ResponseTemplate::new(200).set_body_string(bulk_response))
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = false;
        let client = HttpClient::try_new(&config).unwrap();
        assert!(!client.gzip_compression());

        let payload = Bytes::from("{\"create\":{}}\n{\"body\":\"plain ndjson\"}\n");
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert!(!resp.errors);
    }

    #[tokio::test]
    async fn test_send_bulk_gzip_decompression_verification() {
        let server = MockServer::start().await;

        let raw_ndjson = "{\"create\":{}}\n{\"service_name\":\"api-gateway\",\"status\":200}\n";

        // Decompress body in matcher callback
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(header("content-encoding", "gzip"))
            .and(move |req: &wiremock::Request| {
                let mut decoder = GzDecoder::new(&req.body[..]);
                let mut decompressed = String::new();
                if decoder.read_to_string(&mut decompressed).is_ok() {
                    decompressed == raw_ndjson
                } else {
                    false
                }
            })
            .respond_with(
                ResponseTemplate::new(200)
                    .set_body_string(r#"{"took": 10, "errors": false, "items": []}"#),
            )
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(raw_ndjson);
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();
        assert!(!resp.errors);
    }

    #[tokio::test]
    async fn test_send_bulk_retry_on_429_then_succeeds() {
        let server = MockServer::start().await;

        // First attempt returns 429
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(429).set_body_string("Too Many Requests"))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        // Second attempt returns 200 OK
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(
                ResponseTemplate::new(200)
                    .set_body_string(r#"{"took": 20, "errors": false, "items": []}"#),
            )
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.max_retries = 2;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"create\":{}}\n{\"body\":\"retry test\"}\n");
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();
        assert!(!resp.errors);
    }

    #[tokio::test]
    async fn test_send_bulk_retry_on_503_then_succeeds() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/metrics-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(503).set_body_string("Service Unavailable"))
            .up_to_n_times(2)
            .mount(&server)
            .await;

        Mock::given(method("POST"))
            .and(path("/metrics-otel-default/_bulk"))
            .respond_with(
                ResponseTemplate::new(200)
                    .set_body_string(r#"{"took": 3, "errors": false, "items": []}"#),
            )
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.max_retries = 3;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"create\":{}}\n{\"metric\":\"cpu\"}\n");
        let resp = client
            .send_bulk("metrics-otel-default", payload)
            .await
            .unwrap();
        assert!(!resp.errors);
    }

    #[tokio::test]
    async fn test_send_bulk_retries_exhausted() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(429).set_body_string("cluster saturated"))
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.max_retries = 2;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"create\":{}}\n{\"body\":\"drop me\"}\n");
        let err = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap_err();

        match err {
            ElasticsearchError::BulkFailed { retries, message } => {
                assert_eq!(retries, 2);
                assert!(message.contains("HTTP 429"));
            }
            other => panic!("expected BulkFailed, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_send_bulk_auth_failure_no_retry() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(401).set_body_string("Unauthorized"))
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.max_retries = 3;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"create\":{}}\n{\"body\":\"unauthorized\"}\n");
        let err = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap_err();

        assert!(matches!(err, ElasticsearchError::AuthenticationFailed(_)));
        assert!(err.to_string().contains("HTTP 401"));
    }

    #[tokio::test]
    async fn test_health_check_success() {
        let server = MockServer::start().await;

        let info_json = r#"{
            "name": "opensearch-node-1",
            "cluster_name": "otel-cluster",
            "version": {
                "distribution": "opensearch",
                "number": "2.17.0"
            },
            "tagline": "The OpenSearch Project: https://opensearch.org/"
        }"#;

        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(200).set_body_string(info_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        assert!(client.health_check().await.is_ok());
    }

    #[tokio::test]
    async fn test_health_check_missing_version_number() {
        let server = MockServer::start().await;

        let bad_json = r#"{"name": "broken-node", "version": {}}"#;

        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(200).set_body_string(bad_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let err = client.health_check().await.unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(err.to_string().contains("valid version number"));
    }

    #[tokio::test]
    async fn test_health_check_unauthorized() {
        let server = MockServer::start().await;

        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(403).set_body_string("Forbidden"))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let err = client.health_check().await.unwrap_err();
        assert!(matches!(err, ElasticsearchError::AuthenticationFailed(_)));
        assert!(err.to_string().contains("HTTP 403"));
    }

    #[tokio::test]
    async fn test_validate_index_template_success() {
        let server = MockServer::start().await;

        let template_json = r#"{
            "index_templates": [
                {
                    "name": "logs-otel-default",
                    "index_template": {
                        "index_patterns": ["logs-otel-default*"],
                        "data_stream": {}
                    }
                }
            ]
        }"#;

        Mock::given(method("GET"))
            .and(path("/_index_template/logs-otel-default"))
            .respond_with(ResponseTemplate::new(200).set_body_string(template_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        assert!(
            client
                .validate_index_template("logs-otel-default")
                .await
                .is_ok()
        );
    }

    #[tokio::test]
    async fn test_validate_index_template_not_found() {
        let server = MockServer::start().await;

        Mock::given(method("GET"))
            .and(path("/_index_template/missing-template"))
            .respond_with(ResponseTemplate::new(404).set_body_string("Not Found"))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let err = client
            .validate_index_template("missing-template")
            .await
            .unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(err.to_string().contains("not found (HTTP 404)"));
    }

    #[tokio::test]
    async fn test_validate_index_template_unauthorized() {
        let server = MockServer::start().await;

        Mock::given(method("GET"))
            .and(path("/_index_template/traces-otel-default"))
            .respond_with(ResponseTemplate::new(401).set_body_string("Unauthorized"))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let err = client
            .validate_index_template("traces-otel-default")
            .await
            .unwrap_err();
        assert!(matches!(err, ElasticsearchError::AuthenticationFailed(_)));
        assert!(err.to_string().contains("HTTP 401"));
    }

    #[tokio::test]
    async fn test_validate_index_template_empty_array() {
        let server = MockServer::start().await;

        let template_json = r#"{"index_templates": []}"#;

        Mock::given(method("GET"))
            .and(path("/_index_template/logs-otel-default"))
            .respond_with(ResponseTemplate::new(200).set_body_string(template_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let err = client
            .validate_index_template("logs-otel-default")
            .await
            .unwrap_err();
        assert!(matches!(err, ElasticsearchError::StartupValidation(_)));
        assert!(err.to_string().contains("empty template list"));
    }

    #[cfg(feature = "aws")]
    #[test]
    fn test_auth_headers_aws_sigv4() {
        let mut config = make_test_config(vec![
            "https://search-my-cluster.us-east-1.es.amazonaws.com".to_string(),
        ]);
        config.auth = ElasticsearchAuthConfig::AwsSigv4 {
            region: "us-east-1".to_string(),
            service: "es".to_string(),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client
            .client
            .post("https://search-my-cluster.us-east-1.es.amazonaws.com/logs-otel-default/_bulk");
        let req = client.apply_aws_sigv4(
            req,
            "POST",
            "https://search-my-cluster.us-east-1.es.amazonaws.com/logs-otel-default/_bulk",
            b"{\"index\":{}}\n{\"msg\":\"hello\"}\n",
            "us-east-1",
            "es",
            "AKIAIOSFODNN7EXAMPLE",
            "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
            None,
        );
        let request = req.build().unwrap();

        let auth_hdr = request
            .headers()
            .get("authorization")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(auth_hdr.starts_with("AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/"));
        assert!(auth_hdr.contains("/us-east-1/es/aws4_request"));
        assert!(auth_hdr.contains("SignedHeaders="));
        assert!(auth_hdr.contains("Signature="));

        let date_hdr = request
            .headers()
            .get("x-amz-date")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(!date_hdr.is_empty());
        assert!(request.headers().get("x-amz-security-token").is_none());
    }

    #[cfg(feature = "aws")]
    #[test]
    fn test_auth_headers_aws_sigv4_with_session_token() {
        let mut config = make_test_config(vec![
            "https://search-my-cluster.us-east-1.es.amazonaws.com".to_string(),
        ]);
        config.auth = ElasticsearchAuthConfig::AwsSigv4 {
            region: "us-east-1".to_string(),
            service: "es".to_string(),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client
            .client
            .get("https://search-my-cluster.us-east-1.es.amazonaws.com/");
        let req = client.apply_aws_sigv4(
            req,
            "GET",
            "https://search-my-cluster.us-east-1.es.amazonaws.com/",
            &[],
            "us-east-1",
            "es",
            "AKIAIOSFODNN7EXAMPLE",
            "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
            Some("AQoDYXdzEJr1EXAMPLETOKEN"),
        );
        let request = req.build().unwrap();

        let auth_hdr = request
            .headers()
            .get("authorization")
            .unwrap()
            .to_str()
            .unwrap();
        assert!(auth_hdr.starts_with("AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/"));

        let token_hdr = request
            .headers()
            .get("x-amz-security-token")
            .unwrap()
            .to_str()
            .unwrap();
        assert_eq!(token_hdr, "AQoDYXdzEJr1EXAMPLETOKEN");
    }

    #[cfg(feature = "aws")]
    #[test]
    fn test_auth_headers_aws_sigv4_env_missing_passes_through() {
        let mut config = make_test_config(vec![
            "https://search-my-cluster.us-east-1.es.amazonaws.com".to_string(),
        ]);
        config.auth = ElasticsearchAuthConfig::AwsSigv4 {
            region: "us-east-1".to_string(),
            service: "es".to_string(),
        };
        let client = HttpClient::try_new(&config).unwrap();

        let req = client
            .client
            .get("https://search-my-cluster.us-east-1.es.amazonaws.com/");
        // When AWS env credentials are not set, apply_auth_request leaves request untouched
        let req = client.apply_auth(req);
        let request = req.build().unwrap();

        // If env vars were not present, no authorization header should be injected
        if std::env::var("AWS_ACCESS_KEY_ID").is_err() {
            assert!(request.headers().get("authorization").is_none());
        }
    }

    #[tokio::test]
    async fn test_send_bulk_data_stream_slash_sanitization() {
        let server = MockServer::start().await;

        let bulk_response_json = r#"{
            "took": 10,
            "errors": false,
            "items": []
        }"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(200).set_body_string(bulk_response_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"index\":{}}\n{\"message\":\"test\"}\n");
        let res = client.send_bulk("/logs-otel-default/", payload).await;
        assert!(res.is_ok());
    }

    #[tokio::test]
    async fn test_validate_index_template_data_stream_slash_sanitization() {
        let server = MockServer::start().await;

        let template_json = r#"{
            "index_templates": [
                {
                    "name": "logs-otel-default",
                    "index_template": {
                        "index_patterns": ["logs-otel-default*"],
                        "data_stream": {}
                    }
                }
            ]
        }"#;

        Mock::given(method("GET"))
            .and(path("/_index_template/logs-otel-default"))
            .respond_with(ResponseTemplate::new(200).set_body_string(template_json))
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let res = client.validate_index_template("/logs-otel-default/").await;
        assert!(res.is_ok());
    }

    #[tokio::test]
    async fn test_gzip_response_decompression() {
        let server = MockServer::start().await;

        let bulk_response_json = r#"{
            "took": 25,
            "errors": false,
            "items": [
                {
                    "create": {
                        "_index": "logs-otel-default-2026.09.16-000001",
                        "_id": "doc_gzip",
                        "status": 201
                    }
                }
            ]
        }"#;

        let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        std::io::Write::write_all(&mut encoder, bulk_response_json.as_bytes()).unwrap();
        let gzipped_bytes = encoder.finish().unwrap();

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(
                ResponseTemplate::new(200)
                    .insert_header("Content-Encoding", "gzip")
                    .set_body_bytes(gzipped_bytes),
            )
            .mount(&server)
            .await;

        let config = make_test_config(vec![server.uri()]);
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from("{\"index\":{}}\n{\"msg\":\"hello\"}\n");
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert_eq!(resp.took, 25);
        assert!(!resp.errors);
        assert_eq!(resp.items.len(), 1);
        assert_eq!(resp.items[0].status(), Some(201));
    }

    #[test]
    fn test_extract_sub_payload_single_item() {
        let payload = b"{\"create\":{}}\n{\"message\":\"hello world\"}\n";
        let sub = extract_sub_payload(payload, &[0]).unwrap();
        assert_eq!(sub.as_ref(), payload);
    }

    #[test]
    fn test_extract_sub_payload_empty_indices() {
        let payload = b"{\"create\":{}}\n{\"message\":\"hello\"}\n";
        let sub = extract_sub_payload(payload, &[]).unwrap();
        assert!(sub.is_empty());
    }

    #[test]
    fn test_extract_sub_payload_multiple_items_and_reordering() {
        let payload = b"{\"create\":{}}\n{\"id\":\"doc0\"}\n\
                        {\"create\":{}}\n{\"id\":\"doc1\"}\n\
                        {\"create\":{}}\n{\"id\":\"doc2\"}\n";

        // Extract item 1 only
        let sub1 = extract_sub_payload(payload, &[1]).unwrap();
        let expected1 = b"{\"create\":{}}\n{\"id\":\"doc1\"}\n";
        assert_eq!(sub1.as_ref(), expected1);

        // Extract items 0 and 2
        let sub02 = extract_sub_payload(payload, &[0, 2]).unwrap();
        let expected02 = b"{\"create\":{}}\n{\"id\":\"doc0\"}\n\
                          {\"create\":{}}\n{\"id\":\"doc2\"}\n";
        assert_eq!(sub02.as_ref(), expected02);

        // Extract item 2 only
        let sub2 = extract_sub_payload(payload, &[2]).unwrap();
        let expected2 = b"{\"create\":{}}\n{\"id\":\"doc2\"}\n";
        assert_eq!(sub2.as_ref(), expected2);
    }

    #[test]
    fn test_extract_sub_payload_out_of_bounds() {
        let payload = b"{\"create\":{}}\n{\"id\":\"doc0\"}\n";
        let err = extract_sub_payload(payload, &[1]).unwrap_err();
        assert!(matches!(err, ElasticsearchError::Serialization(_)));
        assert!(err.to_string().contains("out of bounds"));
    }

    #[test]
    fn test_extract_sub_payload_odd_lines_error() {
        let payload = b"{\"create\":{}}\n{\"id\":\"doc0\"}\n{\"create\":{}}\n";
        let err = extract_sub_payload(payload, &[0]).unwrap_err();
        assert!(matches!(err, ElasticsearchError::Serialization(_)));
        assert!(err.to_string().contains("odd number of lines"));
    }

    #[test]
    fn test_extract_sub_payload_trailing_newlines_ignored() {
        let payload = b"{\"create\":{}}\n{\"id\":\"doc0\"}\n\n\n";
        let sub = extract_sub_payload(payload, &[0]).unwrap();
        assert_eq!(sub.as_ref(), b"{\"create\":{}}\n{\"id\":\"doc0\"}\n");
    }

    #[test]
    fn test_bulk_item_wrapper_recoverable_and_unrecoverable() {
        let item_200 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 200,
                error: None,
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(!item_200.is_recoverable());
        assert!(!item_200.is_unrecoverable());

        let item_201 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 201,
                error: None,
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(!item_201.is_recoverable());
        assert!(!item_201.is_unrecoverable());

        let item_429 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 429,
                error: Some(BulkItemError {
                    error_type: "es_rejected_execution_exception".to_string(),
                    reason: "queue full".to_string(),
                    caused_by: None,
                }),
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(item_429.is_recoverable());
        assert!(!item_429.is_unrecoverable());

        let item_503 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 503,
                error: None,
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(item_503.is_recoverable());
        assert!(!item_503.is_unrecoverable());

        let item_400 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 400,
                error: Some(BulkItemError {
                    error_type: "mapper_parsing_exception".to_string(),
                    reason: "bad field".to_string(),
                    caused_by: None,
                }),
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(!item_400.is_recoverable());
        assert!(item_400.is_unrecoverable());

        let item_500 = BulkItemWrapper {
            create: Some(BulkItem {
                index: None,
                id: None,
                status: 500,
                error: None,
            }),
            index: None,
            update: None,
            delete: None,
        };
        assert!(!item_500.is_recoverable());
        assert!(item_500.is_unrecoverable());
    }

    #[test]
    fn test_bulk_response_counts() {
        let resp = BulkResponse {
            took: 12,
            errors: true,
            items: vec![
                BulkItemWrapper {
                    create: Some(BulkItem {
                        index: None,
                        id: None,
                        status: 201,
                        error: None,
                    }),
                    index: None,
                    update: None,
                    delete: None,
                },
                BulkItemWrapper {
                    create: Some(BulkItem {
                        index: None,
                        id: None,
                        status: 429,
                        error: None,
                    }),
                    index: None,
                    update: None,
                    delete: None,
                },
                BulkItemWrapper {
                    create: Some(BulkItem {
                        index: None,
                        id: None,
                        status: 503,
                        error: None,
                    }),
                    index: None,
                    update: None,
                    delete: None,
                },
                BulkItemWrapper {
                    create: Some(BulkItem {
                        index: None,
                        id: None,
                        status: 400,
                        error: None,
                    }),
                    index: None,
                    update: None,
                    delete: None,
                },
            ],
        };

        assert_eq!(resp.recoverable_count(), 2);
        assert_eq!(resp.unrecoverable_count(), 1);
    }

    #[tokio::test]
    async fn test_send_bulk_partial_retry_mixed_200_429_400() {
        let server = MockServer::start().await;

        let resp_initial = r#"{
            "took": 10,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc1", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc2", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue saturated"}}},
                {"create": {"_index": "logs", "_id": "doc3", "status": 400, "error": {"type": "mapper_parsing_exception", "reason": "invalid field"}}}
            ]
        }"#;

        let resp_retry = r#"{
            "took": 5,
            "errors": false,
            "items": [
                {"create": {"_index": "logs", "_id": "doc2", "status": 201}}
            ]
        }"#;

        // First attempt contains all 3 documents
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                body_str.contains("doc1") && body_str.contains("doc2") && body_str.contains("doc3")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_initial))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        // Retry attempt must contain ONLY the failed recoverable doc2
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                !body_str.contains("doc1")
                    && body_str.contains("doc2")
                    && !body_str.contains("doc3")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_retry))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = false;
        config.max_retries = 2;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(
            "{\"create\":{}}\n{\"id\":\"doc1\",\"msg\":\"one\"}\n\
             {\"create\":{}}\n{\"id\":\"doc2\",\"msg\":\"two\"}\n\
             {\"create\":{}}\n{\"id\":\"doc3\",\"msg\":\"three\"}\n",
        );
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert_eq!(resp.items.len(), 3);
        assert_eq!(resp.items[0].status(), Some(201));
        assert_eq!(resp.items[1].status(), Some(201)); // Succeeded on retry!
        assert_eq!(resp.items[2].status(), Some(400)); // Logged unrecoverable error
        assert!(resp.errors); // True because item 2 has status 400
    }

    #[tokio::test]
    async fn test_send_bulk_partial_retry_persistent_429_exhausts_retries() {
        let server = MockServer::start().await;

        let resp_initial = r#"{
            "took": 10,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc1", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc2", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue saturated"}}}
            ]
        }"#;

        let resp_retry = r#"{
            "took": 5,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc2", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue still saturated"}}}
            ]
        }"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                body_str.contains("doc1") && body_str.contains("doc2")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_initial))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                !body_str.contains("doc1") && body_str.contains("doc2")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_retry))
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = false;
        config.max_retries = 2;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(
            "{\"create\":{}}\n{\"id\":\"doc1\"}\n\
             {\"create\":{}}\n{\"id\":\"doc2\"}\n",
        );
        let err = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap_err();

        match err {
            ElasticsearchError::BulkFailed { retries, message } => {
                assert_eq!(retries, 2);
                assert!(message.contains("recoverable status (429/503) after 2 retries"));
            }
            other => panic!("expected BulkFailed, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_send_bulk_unrecoverable_400_only_no_retry() {
        let server = MockServer::start().await;

        let resp_400 = r#"{
            "took": 8,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc1", "status": 400, "error": {"type": "mapper_parsing_exception", "reason": "bad doc 1"}}},
                {"create": {"_index": "logs", "_id": "doc2", "status": 400, "error": {"type": "mapper_parsing_exception", "reason": "bad doc 2"}}}
            ]
        }"#;

        // Must only receive exactly 1 request because all errors are unrecoverable
        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_400))
            .expect(1)
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = false;
        config.max_retries = 3;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(
            "{\"create\":{}}\n{\"id\":\"doc1\"}\n\
             {\"create\":{}}\n{\"id\":\"doc2\"}\n",
        );
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert!(resp.errors);
        assert_eq!(resp.items.len(), 2);
        assert_eq!(resp.items[0].status(), Some(400));
        assert_eq!(resp.items[1].status(), Some(400));
    }

    #[tokio::test]
    async fn test_send_bulk_partial_retry_multiple_rounds() {
        let server = MockServer::start().await;

        // Attempt 0: 4 items (doc0, doc1, doc2, doc3). doc1 and doc3 fail with 429
        let resp_attempt0 = r#"{
            "took": 10,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc0", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc1", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue full"}}},
                {"create": {"_index": "logs", "_id": "doc2", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc3", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue full"}}}
            ]
        }"#;

        // Attempt 1 (Retry 1): sub-payload of doc1, doc3. doc1 succeeds, doc3 still 429
        let resp_attempt1 = r#"{
            "took": 7,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc1", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc3", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue full"}}}
            ]
        }"#;

        // Attempt 2 (Retry 2): sub-payload of doc3 only. doc3 succeeds!
        let resp_attempt2 = r#"{
            "took": 4,
            "errors": false,
            "items": [
                {"create": {"_index": "logs", "_id": "doc3", "status": 201}}
            ]
        }"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                body_str.contains("doc0")
                    && body_str.contains("doc1")
                    && body_str.contains("doc2")
                    && body_str.contains("doc3")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_attempt0))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                !body_str.contains("doc0")
                    && body_str.contains("doc1")
                    && !body_str.contains("doc2")
                    && body_str.contains("doc3")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_attempt1))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(|req: &wiremock::Request| {
                let body_str = String::from_utf8_lossy(&req.body);
                !body_str.contains("doc0")
                    && !body_str.contains("doc1")
                    && !body_str.contains("doc2")
                    && body_str.contains("doc3")
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_attempt2))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = false;
        config.max_retries = 3;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(
            "{\"create\":{}}\n{\"id\":\"doc0\"}\n\
             {\"create\":{}}\n{\"id\":\"doc1\"}\n\
             {\"create\":{}}\n{\"id\":\"doc2\"}\n\
             {\"create\":{}}\n{\"id\":\"doc3\"}\n",
        );
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert_eq!(resp.items.len(), 4);
        assert_eq!(resp.items[0].status(), Some(201));
        assert_eq!(resp.items[1].status(), Some(201));
        assert_eq!(resp.items[2].status(), Some(201));
        assert_eq!(resp.items[3].status(), Some(201));
        assert!(!resp.errors);
    }

    #[tokio::test]
    async fn test_send_bulk_partial_retry_with_gzip() {
        let server = MockServer::start().await;

        let resp_initial = r#"{
            "took": 15,
            "errors": true,
            "items": [
                {"create": {"_index": "logs", "_id": "doc1", "status": 201}},
                {"create": {"_index": "logs", "_id": "doc2", "status": 429, "error": {"type": "es_rejected_execution_exception", "reason": "queue full"}}}
            ]
        }"#;

        let resp_retry = r#"{
            "took": 5,
            "errors": false,
            "items": [
                {"create": {"_index": "logs", "_id": "doc2", "status": 201}}
            ]
        }"#;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(header("content-encoding", "gzip"))
            .and(|req: &wiremock::Request| {
                let mut decoder = GzDecoder::new(&req.body[..]);
                let mut decompressed = String::new();
                if decoder.read_to_string(&mut decompressed).is_ok() {
                    decompressed.contains("doc1") && decompressed.contains("doc2")
                } else {
                    false
                }
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_initial))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        Mock::given(method("POST"))
            .and(path("/logs-otel-default/_bulk"))
            .and(header("content-encoding", "gzip"))
            .and(|req: &wiremock::Request| {
                let mut decoder = GzDecoder::new(&req.body[..]);
                let mut decompressed = String::new();
                if decoder.read_to_string(&mut decompressed).is_ok() {
                    !decompressed.contains("doc1") && decompressed.contains("doc2")
                } else {
                    false
                }
            })
            .respond_with(ResponseTemplate::new(200).set_body_string(resp_retry))
            .up_to_n_times(1)
            .mount(&server)
            .await;

        let mut config = make_test_config(vec![server.uri()]);
        config.gzip_compression = true;
        config.max_retries = 2;
        let client = HttpClient::try_new(&config).unwrap();

        let payload = Bytes::from(
            "{\"create\":{}}\n{\"id\":\"doc1\"}\n\
             {\"create\":{}}\n{\"id\":\"doc2\"}\n",
        );
        let resp = client
            .send_bulk("logs-otel-default", payload)
            .await
            .unwrap();

        assert_eq!(resp.items.len(), 2);
        assert_eq!(resp.items[0].status(), Some(201));
        assert_eq!(resp.items[1].status(), Some(201));
        assert!(!resp.errors);
    }
}
